---
name: Link Checker

on:
  push: null
  repository_dispatch: null
  workflow_dispatch: null
permissions:
  contents: read
jobs:
  linkChecker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Link Checker
        id: lychee
        uses: lycheeverse/lychee-action@v2
        with:
          args: >-
            './**/*.md'
            --verbose
            --no-progress
            --user-agent 'Mozilla/5.0 (X11; Linux x86_64) Chrome/134.0.0.0'
            --retry-wait-time 30
            --max-retries 5
            --accept 100..=103,200..=299,429
            --cookie-jar cookies.json
            --exclude-all-private
          format: markdown
          fail: true
